name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: scripts/version-tag-validate.js ${{ github.ref }}
      - run: yarn test --ci
      - run: yarn lint
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
